import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
import {  signOut, useSession } from "next-auth/react";

// import { api } from "@/utils/api";
import { Button } from "@/components";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const session = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center text-white ">
        <h1>Home Page</h1>
        {JSON.stringify(session, null, 2)}
        <Button
          onClick={() =>
            void signOut({
              callbackUrl: "/auth/login",
              redirect: true,

            })
          }
        >
          sign out
        </Button>
      </main>
    </>
  );
};

export default Home;
